apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: learning-portal
  labels:
    app: analytics-service
spec:
  ports:
  - port: 8003
    targetPort: 8003
    protocol: TCP
    name: http
  selector:
    app: analytics-service
  type: ClusterIP
