apiVersion: v1
kind: ConfigMap
metadata:
  name: global-configmap
  namespace: learning-portal
  labels:
    app: learning-portal
data:
  # Base Configurations
  MONGO_INITDB_ROOT_USERNAME: "admin"
  POSTGRES_USER: "admin"
  POSTGRES_DB: "learning_db"
  MINIO_ROOT_USER: "minioadmin"
  
  # Services URLs / Ports
  USER_SERVICE_PORT: "8002"
  COURSE_SERVICE_PORT: "8001"
  ANALYTICS_SERVICE_PORT: "8003"
  AI_TUTOR_SERVICE_PORT: "8004"
  LEARNING_PORTAL_PORT: "3000"
  
  # Connection URIs (using K8s internal DNS names)
  MONGODB_URI: "mongodb://admin:mongodb123@mongodb:27017/users?authSource=admin"
  DATABASE_URL: "postgresql://admin:postgres123@postgres:5432/learning_db"
  
  # Next.js Public Env Variables (usually routed via the gateway)
  NEXT_PUBLIC_USER_SERVICE_URL: "/api"
  NEXT_PUBLIC_COURSE_SERVICE_URL: "/api"
