apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: learning-portal
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: nawreszarrouki/user-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: global-configmap
              key: USER_SERVICE_PORT
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: global-configmap
              key: MONGODB_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: JWT_SECRET
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
