apiVersion: v1
kind: Service
metadata:
  name: course-service
  namespace: learning-portal
  labels:
    app: course-service
spec:
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: course-service
  type: ClusterIP
