apiVersion: v1
kind: Service
metadata:
  name: learning-portal
  namespace: learning-portal
  labels:
    app: learning-portal
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: learning-portal
  type: ClusterIP
